version: '3.1'

services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tooth-history
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5555:5432'

volumes:
  postgres:

